version: "3.7"
services:
    db:
        image: postgres:13
        container_name: container_postgres_scraper_google_flight
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: scraping-google-flight
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        networks:
            - internal
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 20s
            timeout: 20s
            retries: 5
        ports:
            - "5432:5432"
        restart: always
    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: scraper_google_flight_node
        container_name: container_node_scraper_google_flight
        networks:
            - default
            - internal
        depends_on:
            db:
                condition: service_healthy
        ports:
            - "4000:4000"

networks:
    internal:
        internal: true